param(
    [Parameter(Mandatory = $true)]
    [string]$Action,

    [string]$Distro,

    [string]$Arg1,

    [string]$Arg2,

    [string]$Arg3
)

$ErrorActionPreference = 'Stop'

#===================================================================================
#===================================================================================
# Runs a root bash command in the selected WSL distro and returns combined output.
function Invoke-WslCommand {
    param(
        [Parameter(Mandatory = $true)]
        [string]$DistroName,

        [Parameter(Mandatory = $true)]
        [string]$CommandText
    )

    # PowerShell here-strings keep the script file's CRLF endings. bash treats the
    # carriage return as part of the token, which breaks loops as "do\r".
    $normalizedCommandText = $CommandText.Replace("`r`n", "`n").Replace("`r", "`n")

    # Keep WSL calls inside a normal PowerShell process. Direct wsl.exe calls from
    # the batch launcher were tripping "Input redirection is not supported" in this
    # automation host even when the same command worked interactively.
    $escaped = $normalizedCommandText.Replace('"', '\"')
    $standardOutput = & wsl.exe -d $DistroName -u root -- bash -lc "exec 0</dev/null; $escaped" 2>&1
    $combinedOutput = @($standardOutput) -join [Environment]::NewLine

    return [PSCustomObject]@{
        ExitCode = $LASTEXITCODE
        StdOut = $combinedOutput
        StdErr = ''
    }
}

function Escape-BashSingleQuotedText {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Value
    )

    return $Value.Replace("'", "'\''")
}

#===================================================================================
#===================================================================================
# Converts a user-facing interface string into individual WSL interface names.
function ConvertTo-InterfaceList {
    param(
        [Parameter(Mandatory = $true)]
        [string]$InterfacesText
    )

    return @($InterfacesText.Split(@(' ', "`t", ',', ';'), [System.StringSplitOptions]::RemoveEmptyEntries))
}

#===================================================================================
#===================================================================================
# Builds the pgrep match pattern for a GS process launched with the selected interfaces.
function Get-WslGsMatchPattern {
    param(
        [Parameter(Mandatory = $true)]
        [string]$InterfacesText
    )

    $interfaces = @(ConvertTo-InterfaceList -InterfacesText $InterfacesText)
    if ($interfaces.Count -eq 0) {
        return "^./gs .* -fullscreen 0 -sm 1`$"
    }

    $rxPattern = (($interfaces | ForEach-Object { [regex]::Escape($_) }) -join " ")
    $txPattern = [regex]::Escape($interfaces[0])

    return "^./gs -rx $rxPattern -tx $txPattern -fullscreen 0 -sm 1`$"
}

#===================================================================================
#===================================================================================
# Builds the bash command that launches GS with all selected RX interfaces.
function New-WslGsCommand {
    param(
        [Parameter(Mandatory = $true)]
        [string]$GsDir,

        [Parameter(Mandatory = $true)]
        [string]$InterfacesText
    )

    $interfaces = @(ConvertTo-InterfaceList -InterfacesText $InterfacesText)
    if ($interfaces.Count -eq 0) {
        throw 'No WSL Wi-Fi interfaces were provided.'
    }

    # Interface names are generated by Linux (wlan*/wlx*) and contain no shell
    # metacharacters. Nested cmd.exe/bash quoting truncated the quoted TX name to
    # its first character, so keep these generated arguments unquoted.
    $rxArgs = $interfaces -join ' '
    $txInterface = $interfaces[0]

    return "cd '$GsDir' && exec ./gs -rx $rxArgs -tx $txInterface -fullscreen 0 -sm 1"
}

function Stop-WslGsInstance {
    param(
        [Parameter(Mandatory = $true)]
        [string]$DistroName,

        [Parameter(Mandatory = $true)]
        [string]$MatchPattern,

        [string]$PidPath = "/tmp/gs-wsl-mcp.pid"
    )

    # Do not use pkill -f with the full GS command text here. The helper itself runs
    # a bash -lc command containing the same pattern, so pkill would match its shell.
    $stopCommand = "pgrep -f '$MatchPattern' | xargs -r kill >/dev/null 2>&1 || true; rm -f '$PidPath' /tmp/gs-wsl-mcp.log"
    return Invoke-WslCommand -DistroName $DistroName -CommandText $stopCommand
}

function Start-WslGsMcpInstance {
    param(
        [Parameter(Mandatory = $true)]
        [string]$DistroName,

        [Parameter(Mandatory = $true)]
        [string]$GsDir,

        [Parameter(Mandatory = $true)]
        [string]$InterfacesText
    )

    # Detached WSL launches were unstable in testing: GS could bring up MCP and then
    # disappear immediately. Keep GS in its own visible WSL console so SDL/WSLg stay
    # attached to an interactive session, while the helper polls MCP separately.
    $gsCommand = New-WslGsCommand -GsDir $GsDir -InterfacesText $InterfacesText
    $cmdLine = "/c start """" wsl.exe -d $DistroName -u root -- bash -lc ""$gsCommand"""
    $process = Start-Process -FilePath 'cmd.exe' -ArgumentList $cmdLine -PassThru

    return [PSCustomObject]@{
        ExitCode = $(if ($null -eq $process) { 1 } else { 0 })
        StdOut = ''
        StdErr = ''
    }
}

function Get-WslPrimaryIp {
    param(
        [Parameter(Mandatory = $true)]
        [string]$DistroName
    )

    $ipResult = Invoke-WslCommand -DistroName $DistroName -CommandText "hostname -I"
    if ($ipResult.ExitCode -ne 0) {
        return $null
    }

    $tokens = $ipResult.StdOut.Trim().Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries)
    if ($tokens.Count -eq 0) {
        return $null
    }

    return $tokens[0]
}

function Remove-WindowsMcpProxy {
    param(
        [int]$Port = 17654
    )

    & netsh interface portproxy delete v4tov4 listenaddress=127.0.0.1 listenport=$Port | Out-Null
}

function Ensure-WindowsMcpProxy {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ConnectAddress,

        [int]$Port = 17654
    )

    & sc.exe start iphlpsvc | Out-Null
    Remove-WindowsMcpProxy -Port $Port
    & netsh interface portproxy add v4tov4 listenaddress=127.0.0.1 listenport=$Port connectaddress=$ConnectAddress connectport=$Port | Out-Null
    return ($LASTEXITCODE -eq 0)
}

#===================================================================================
#===================================================================================
# Waits for the requested number of WSL Wi-Fi monitor-capable interface names.
function Find-WslWifiInterfaces {
    param(
        [Parameter(Mandatory = $true)]
        [string]$DistroName,

        [int]$TimeoutSeconds = 15,

        [int]$TargetCount = 1
    )

    $TargetCount = [Math]::Max(1, $TargetCount)
$deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
$probeCommand = @'
# AU, EU and BU adapters can be attached together, so load every available driver.
# Stopping after the first module leaves a later adapter without a driver.
for module in 8812eu rtl8812eu rtl8xxxu 88XXau_wfb 88XXau rtl88xxau 8812au 88x2bu rtl88x2bu; do
    modprobe "$module" >/dev/null 2>&1 || true
done
udevadm settle --timeout=3 >/dev/null 2>&1 || true
ls /sys/class/net 2>/dev/null | grep -E '^(wlx|wlan)' | sort
'@

    do {
        $result = Invoke-WslCommand -DistroName $DistroName -CommandText $probeCommand
        $ifaces = @($result.StdOut.Trim().Split([Environment]::NewLine, [System.StringSplitOptions]::RemoveEmptyEntries) |
            ForEach-Object { $_.Trim() } |
            Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
            Select-Object -First $TargetCount)

        if ($ifaces.Count -ge $TargetCount) {
            return $ifaces
        }

        Start-Sleep -Seconds 1
    } while ([DateTime]::UtcNow -lt $deadline)

    return @()
}

switch ($Action) {
    'detect_iface' {
        if ([string]::IsNullOrWhiteSpace($Arg1)) {
            throw 'detect_iface requires an output file path.'
        }

        $timeoutSeconds = 15
        if (-not [string]::IsNullOrWhiteSpace($Arg2)) {
            $timeoutSeconds = [Math]::Max(1, [int]$Arg2)
        }

        $ifaces = Find-WslWifiInterfaces -DistroName $Distro -TimeoutSeconds $timeoutSeconds -TargetCount 1
        if ($ifaces.Count -gt 0) {
            Set-Content -LiteralPath $Arg1 -Value $ifaces[0] -NoNewline
            exit 0
        }

        exit 1
    }

    'detect_ifaces' {
        if ([string]::IsNullOrWhiteSpace($Arg1)) {
            throw 'detect_ifaces requires an output file path.'
        }

        $timeoutSeconds = 15
        if (-not [string]::IsNullOrWhiteSpace($Arg2)) {
            $timeoutSeconds = [Math]::Max(1, [int]$Arg2)
        }

        $targetCount = 1
        if (-not [string]::IsNullOrWhiteSpace($Arg3)) {
            $targetCount = [Math]::Max(1, [int]$Arg3)
        }

        $ifaces = Find-WslWifiInterfaces -DistroName $Distro -TimeoutSeconds $timeoutSeconds -TargetCount $targetCount
        if ($ifaces.Count -ge $targetCount) {
            Set-Content -LiteralPath $Arg1 -Value $ifaces
            exit 0
        }

        exit 1
    }

    'probe_iface_ready' {
        if ([string]::IsNullOrWhiteSpace($Arg1)) {
            throw 'probe_iface_ready requires an interface name.'
        }

        $iface = $Arg1.Replace("'", "'\''")
        $commandText = "ip link show dev '$iface' >/dev/null 2>&1 && " +
            "iw dev '$iface' info >/dev/null 2>&1 && " +
            "ip link set dev '$iface' down >/dev/null 2>&1 && " +
            "iw dev '$iface' set type managed >/dev/null 2>&1 && " +
            "ip link set dev '$iface' up >/dev/null 2>&1"

        $result = Invoke-WslCommand -DistroName $Distro -CommandText $commandText
        exit $result.ExitCode
    }

    'launch_mcp_full' {
        if ([string]::IsNullOrWhiteSpace($Arg1) -or
            [string]::IsNullOrWhiteSpace($Arg2) -or
            [string]::IsNullOrWhiteSpace($Arg3)) {
            throw 'launch_mcp_full requires interfaces, WSL gs dir, and WSL client path.'
        }

        $interfacesText = $Arg1
        $gsDir = Escape-BashSingleQuotedText $Arg2
        $clientPath = Escape-BashSingleQuotedText $Arg3
        $pidPath = "/tmp/gs-wsl-mcp.pid"
        $matchPattern = Get-WslGsMatchPattern -InterfacesText $interfacesText

        $cleanupResult = Stop-WslGsInstance -DistroName $Distro -MatchPattern $matchPattern -PidPath $pidPath
        if ($cleanupResult.ExitCode -ne 0) {
            exit $cleanupResult.ExitCode
        }

        $launchResult = Start-WslGsMcpInstance -DistroName $Distro -GsDir $gsDir -InterfacesText $interfacesText
        if ($launchResult.ExitCode -ne 0) {
            exit $launchResult.ExitCode
        }

        $deadline = [DateTime]::UtcNow.AddSeconds(30)
        Start-Sleep -Milliseconds 1500
        while ([DateTime]::UtcNow -lt $deadline) {
            $gsPidLookup = Invoke-WslCommand -DistroName $Distro -CommandText ("pgrep -n -f '$MatchPattern'")
            $gsPid = $gsPidLookup.StdOut.Trim()
            if (-not [string]::IsNullOrWhiteSpace($gsPid)) {
                $writePid = Invoke-WslCommand -DistroName $Distro -CommandText ("echo '{0}' > '{1}'" -f $gsPid, $pidPath)
                if ($writePid.ExitCode -eq 0) {
                    $clientResult = Invoke-WslCommand -DistroName $Distro -CommandText ("python3 '{0}' tools-list >/dev/null 2>&1" -f $clientPath)
                    if ($clientResult.ExitCode -eq 0) {
                        $wslIp = Get-WslPrimaryIp -DistroName $Distro
                        if ([string]::IsNullOrWhiteSpace($wslIp)) {
                            exit 1
                        }

                        if (-not (Ensure-WindowsMcpProxy -ConnectAddress $wslIp)) {
                            exit 1
                        }

                        Write-Output ("READY:" + $gsPid + ":" + $wslIp)
                        exit 0
                    }
                }
            }

            Start-Sleep -Milliseconds 500
        }

        exit 1
    }

    'stop_mcp' {
        $matchPattern = "^./gs .* -fullscreen 0 -sm 1`$"
        $stopResult = Stop-WslGsInstance -DistroName $Distro -MatchPattern $matchPattern
        Remove-WindowsMcpProxy
        exit 0
    }

    'mcp_ready' {
        if ([string]::IsNullOrWhiteSpace($Arg1)) {
            throw 'mcp_ready requires the WSL MCP client path.'
        }

        $clientPath = Escape-BashSingleQuotedText $Arg1
        $clientResult = Invoke-WslCommand -DistroName $Distro -CommandText ("python3 '{0}' tools-list >/dev/null 2>&1" -f $clientPath)
        exit $clientResult.ExitCode
    }

    default {
        throw "Unsupported action '$Action'."
    }
}
